#!/usr/bin/env bash
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"
export SDN_NIDS_DASHBOARD_HOST="${SDN_NIDS_DASHBOARD_HOST:-0.0.0.0}"
export SDN_NIDS_DASHBOARD_PORT="${SDN_NIDS_DASHBOARD_PORT:-8050}"
export SDN_NIDS_DASHBOARD_STREAM_HOST="${SDN_NIDS_DASHBOARD_STREAM_HOST:-127.0.0.1}"
export SDN_NIDS_DASHBOARD_STREAM_PORT="${SDN_NIDS_DASHBOARD_STREAM_PORT:-8765}"
exec bash scripts/run_dashboard.sh
